services:
  api_context:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/api_context"
      - "/opt/api_context/node_modules"
    environment:
      - NEXT_WEBPACK_USEPOLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true